require('dotenv').config();
const { JWT } = require('google-auth-library');
const { GoogleSpreadsheet } = require('google-spreadsheet')

//구글 sheet json 파일
const i18nextConfig = require('../../i18next-scanner.config')
const spreadsheetDocId = '1wflhbmWZEudZSqERyM7-jkVHNxL_5EtuGcv9HXRqZYQ'
const ns = 'translation'
const lngs = i18nextConfig.options.lngs

//구글 스프레드시트의 gid
const sheetId = 0
const loadPath = i18nextConfig.options.resource.loadPath
// 개발서버에서 사용하면 제대로 인식을 못해 아래처럼 수정
// const localesPath = loadPath.replace("\\{{lng}}\\{{ns}}.json", '')
const localeIdx = loadPath.indexOf('locales')
const localesPath = loadPath.substring(0, localeIdx + 7)
const rePluralPostfix = new RegExp(/_plural|_[\d]/g)
//번역이 필요없는 부분
const NOT_AVAILABLE_CELL = 'N/A'

//스프레드시트에 들어갈 header 설정
const columnKeyToHeader = {
  key: '키',
  ko: '한글',
  en: '영어',
  es: '에스파냐어',
  jp: '일본어',
}

async function loadSpreadsheet() {
  // eslint-disable-next-line no-console
  console.info(
    '\u001B[32m',
    '=====================================================================================================================\n',
    '# i18next auto-sync using Spreadsheet\n\n',
    '  * Download translation resources from Spreadsheet and make /src/locales//.json\n',
    '  * Upload translation resources to Spreadsheet.\n\n',
    `The Spreadsheet for translation is here (\u001B[34mhttps://docs.google.com/spreadsheets/d/${spreadsheetDocId}/#gid=${sheetId}\u001B[0m)\n`,
    '=====================================================================================================================',
    '\u001B[0m'
  )

 try {
   const serviceAccountAuth = new JWT({
     // env var values here are copied from service account credentials generated by google
     // see "Authentication" section in docs for more info
     email: process.env.TRANSLATION_PRIVATE_API_CLIENT_EMAIL,
     key: process.env.TRANSLATION_PRIVATE_API_KEY,
     scopes: [
       'https://www.googleapis.com/auth/spreadsheets',
     ],
   });

   const doc = new GoogleSpreadsheet(spreadsheetDocId, serviceAccountAuth);
   await doc.loadInfo() // loads document properties and worksheets
   return doc
 } catch (err) {
    console.log('err', err);
 }
}

function getPureKey(key = '') {
  return key.replace(rePluralPostfix, '')
}

module.exports = {
  localesPath,
  loadSpreadsheet,
  getPureKey,
  ns,
  lngs,
  sheetId,
  columnKeyToHeader,
  NOT_AVAILABLE_CELL,
}